# Generated by Django 2.2 on 2019-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190409_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('hiking_trail', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=10000)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('reviewss', models.ManyToManyField(to='reviews.Review')),
            ],
        ),
    ]
