# Generated by Django 2.2 on 2019-04-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reviewss',
            new_name='reviews',
        ),
    ]
