# Generated by Django 2.2 on 2019-04-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20190416_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='reviews.Tag'),
        ),
    ]
