# Generated by Django 2.2 on 2019-06-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
        migrations.RemoveField(
            model_name='image',
            name='review',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='reviews.Image'),
        ),
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.ManyToManyField(to='reviews.Image'),
        ),
    ]
