# Generated by Django 2.2 on 2019-06-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20190603_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='small_blurb',
            field=models.CharField(default="Lorem ipsum dolor amet plaid deep v crucifix austin, fanny pack snackwave PBR&B post-ironic bicycle rights kale chips pitchfork tousled. Etsy kinfolk shaman chambray distillery. Skateboard slow-carb vegan microdosing viral plaid. Williamsburg everyday carry irony, fam health goth +1 hammock flannel hell of raw denim pork belly 8-bit. Drinking vinegar poutine man braid chartreuse disrupt artisan roof party brunch humblebrag pour-over. Skateboard lo-fi iPhone typewriter literally bicycle rights kitsch readymade four loko vice franzen. Chambray cornhole fashion axe, fingerstache meh gentrify leggings prism austin kale chips kombucha etsy mumblecore hammock 90's. Gastropub DIY paleo, helvetica keffiyeh cray hella chicharrones post-ironic you probably haven't heard of them la croix man bun hoodie keytar meditation. Etsy shabby chic", max_length=500),
            preserve_default=False,
        ),
    ]
